[build]
  publish = "."
  command = "echo 'No build needed - static HTML'"

# Center-specific routes for targeted advertising
[[redirects]]
  from = "/barcelona-sants"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/valencia"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/madrid-atocha"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/madrid-chamartin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sevilla"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/majadahonda"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/san-sebastian"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/torrejon"
  to = "/index.html"
  status = 200

# Catch-all redirect (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
